2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Configure stats pid to 4845
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Loading settings from /root/autodl-tmp/GREAD/src/wandb/settings
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'mode': 'run'}
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run_GNN.py', 'program_abspath': '/root/autodl-tmp/GREAD/src/run_GNN.py', 'program': 'run_GNN.py'}
2024-08-11 13:32:20,413 INFO    MainThread:4845 [wandb_init.py:_log_setup():526] Logging user logs to /root/autodl-tmp/GREAD/src/wandb/run-20240811_133220-sz6ykdg4/logs/debug.log
2024-08-11 13:32:20,414 INFO    MainThread:4845 [wandb_init.py:_log_setup():527] Logging internal logs to /root/autodl-tmp/GREAD/src/wandb/run-20240811_133220-sz6ykdg4/logs/debug-internal.log
2024-08-11 13:32:20,414 INFO    MainThread:4845 [wandb_init.py:init():566] calling init triggers
2024-08-11 13:32:20,414 INFO    MainThread:4845 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'use_best_params': False, 'gpu': 0, 'epoch': 100, 'patience': None, 'optimizer': 'adam', 'lr': 0.01, 'decay': 0.0005, 'dataset': 'Cora', 'data_norm': 'rw', 'self_loop_weight': 0.0, 'use_labels': False, 'label_rate': 0.5, 'planetoid_split': False, 'geom_gcn_splits': False, 'num_splits': 1, 'not_lcc': True, 'hetero_SL': False, 'hetero_undir': False, 'block': 'constant', 'function': 'gread', 'hidden_dim': 64, 'fc_out': False, 'input_dropout': 0.5, 'dropout': 0.0, 'batch_norm': False, 'alpha': 1.0, 'alpha_dim': 'sc', 'no_alpha_sigmoid': False, 'source_dim': 'sc', 'beta_dim': 'sc', 'use_mlp': False, 'add_source': False, 'XN_activation': False, 'm2_mlp': False, 'time': 1.0, 'augment': False, 'method': None, 'step_size': 0.1, 'max_iters': 100, 'adjoint_method': 'adaptive_heun', 'adjoint': False, 'adjoint_step_size': 1, 'tol_scale': 1.0, 'tol_scale_adjoint': 1.0, 'max_nfe': 5000, 'no_early': True, 'earlystopxT': 3, 'max_test_steps': 100, 'jacobian_norm2': None, 'total_deriv': None, 'kinetic_energy': None, 'directional_penalty': None, 'leaky_relu_slope': 0.2, 'attention_dropout': 0.0, 'heads': 1, 'attention_norm_idx': 0, 'attention_dim': 64, 'mix_features': False, 'reweight_attention': False, 'attention_type': 'scaled_dot', 'square_plus': False, 'gcn_fixed': 'False', 'gcn_enc_dec': 'False', 'gcn_non_lin': 'False', 'gcn_symm': 'False', 'gcn_bias': 'False', 'gcn_mid_dropout': 'False', 'gcn_params': None, 'gcn_params_idx': 0, 'rewiring': None, 'gdc_method': 'ppr', 'gdc_sparsification': 'topk', 'gdc_k': 64, 'gdc_threshold': 0.0001, 'gdc_avg_degree': 64, 'ppr_alpha': 0.05, 'heat_time': 3.0, 'att_samp_pct': 1, 'use_flux': False, 'exact': False, 'M_nodes': 64, 'new_edges': 'random', 'sparsify': 'S_hat', 'threshold_type': 'topk_adj', 'rw_addD': 0.02, 'rw_rmvR': 0.02, 'rewire_KNN': False, 'rewire_KNN_T': 'T0', 'rewire_KNN_epoch': 5, 'rewire_KNN_k': 64, 'rewire_KNN_sym': False, 'KNN_online': False, 'KNN_online_reps': 4, 'KNN_space': 'pos_distance', 'pos_enc_csv': False, 'beltrami': False, 'fa_layer': False, 'pos_enc_type': 'GDC', 'pos_enc_orientation': 'row', 'feat_hidden_dim': 64, 'pos_enc_hidden_dim': 32, 'edge_sampling': False, 'edge_sampling_T': 'T0', 'edge_sampling_epoch': 5, 'edge_sampling_add': 0.64, 'edge_sampling_add_type': 'importance', 'edge_sampling_rmv': 0.32, 'edge_sampling_sym': False, 'edge_sampling_online': False, 'edge_sampling_online_reps': 4, 'edge_sampling_space': 'attention', 'reaction_term': 'aggdiff-gat', 'beta_diag': False, 'trusted_mask': False, 'noise': 0.0, 'noise_pos': None, 'prediffuse': False, 'x0': False, 'nox0': False, 'icxb': 1.0, 'source_scale': 1.0, 'alltime': False, 'allnumtrain': False, 'num_train_per_class': 20, 'save_result': False, 'wandb': True, 'wandb_sweep': False, 'wandb_entity': 'username', 'wandb_project': 'example', 'wandb_run_name': None, 'run_track_reports': False, 'save_wandb_reports': False, 'device': device(type='cuda', index=0)}
2024-08-11 13:32:20,414 INFO    MainThread:4845 [wandb_init.py:init():616] starting backend
2024-08-11 13:32:20,414 INFO    MainThread:4845 [wandb_init.py:init():620] setting up manager
2024-08-11 13:32:20,419 INFO    MainThread:4845 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-08-11 13:32:20,420 INFO    MainThread:4845 [wandb_init.py:init():628] backend started and connected
2024-08-11 13:32:20,432 INFO    MainThread:4845 [wandb_init.py:init():720] updated telemetry
2024-08-11 13:32:20,433 INFO    MainThread:4845 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-08-11 13:32:21,778 ERROR   MainThread:4845 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-08-11 13:32:23,782 ERROR   MainThread:4845 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-08-11 13:32:26,779 WARNING MsgRouterThr:4845 [router.py:message_loop():77] message_loop has been closed
